the remaining config changes and change to prepush script

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,3 +1,5 @@
+#! /bin/bash
+
 echo "Running prepush script..."
 
 CMD="yarn prepush" # Command that runs your tests
@@ -12,12 +14,20 @@ fi
 current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
 
 if [[ $current_branch = $protected_branch ]]; then
-    echo "Running yarn prepush in client-api..."
-    (cd client-api && $CMD)
-    RESULT=$?
-    if [ $RESULT -ne 0 ]; then 
-        echo "failed $CMD"
-        exit 1
+    diffedFiles=$(git diff --name-only origin/master..master)
+    echo "$diffedFiles"
+    # Check if there are diffs in client-api
+    if [[ $diffedFiles == *"client-api"* ]];
+    then
+	echo "Running yarn prepush in client-api..."
+	(cd client-api && $CMD)
+	RESULT=$?
+	if [ $RESULT -ne 0 ]; then 
+            echo "failed $CMD"
+            exit 1
+	fi
+    else 
+       echo "No files changed in client-api, skipping client api prepush."
     fi
 fi
 exit 0
